[package]
name = "shigotolog"
version.workspace = true
authors.workspace = true
edition = "2021"

[dependencies]
chrono = "0.4"
regex = "1.11"
rusqlite = { version = "0.32", features = ["bundled", "time", "chrono"] }
